version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      API_URL: http://gateway:8080
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      AUTH_SERVICE: http://auth-service:8081
      MESSAGE_SERVICE: http://message-service:8082
      JWT_SECRET: secret
    depends_on:
      - auth-service
      - message-service

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: communication
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: secret
    depends_on:
      postgres:
        condition: service_healthy

  message-service:
    build:
      context: ./services/message-service
    container_name: message-service
    ports:
      - "8082:8082"
    volumes:
      - ./services/message-service:/app
      - /app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: communication
      DB_USER: postgres
      DB_PASSWORD: postgres

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  notification-service:
    build:
      context: ./services/notificaton-service
    container_name: notification-service
    ports:
      - "8083:8083"
    volumes:
      - ./services/notificaton-service:/app
      - /app/node_modules
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      rabbitmq:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always

    environment:
      POSTGRES_DB: communication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
